### ISSUE TITLE
Remove firstissue.dev Google Analytics tag

### ISSUE THREAD

**Issue by lucavallin** [rubyforgood/happycommits#12]
Hello, and thanks for forking [first-issue](https://github.com/lucavallin/first-issue)!
Can you please remove my Google Analytics tag from your fork? 

https://github.com/rubyforgood/happycommits/blob/bd24cb960c7ccd1873a7ff9f07aa564788f5e4b3/pages/_document.tsx#L37-L49.

**Comment by seanmarcia** [comment]
Done!
